language: elixir
cache:
  directories:
    - deps
elixir:
  - 1.12.1
otp_release:
  - 24.0
matrix:
  include:
    - otp_release: 21.1
      elixir: 1.8.0
    - otp_release: 21.1
      elixir: 1.9.4
    - otp_release: 22.1
      elixir: 1.9.4
    - otp_release: 22.2
      elixir: 1.10.4
    - otp_release: 23.3.1
      elixir: 1.11.4
    - otp_release: 24.0
      elixir: 1.11.4
    - otp_release: 24.0
      elixir: 1.12.1
env:
  global:
    - MIX_ENV=test
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
  # Ensure code is formatted
  - >
    if [[ $(elixir -v) == *"Elixir 1.12.1"* ]]; then
      mix format --check-formatted
    fi
