language: elixir
cache:
  directories:
    - deps
elixir:
  - 1.9.4
otp_release:
  - 21.1
matrix:
  include:
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 21.1
      elixir: 1.7.4
    - otp_release: 22.1
      elixir: 1.9.4
    - otp_release: 22.2
      elixir: 1.10.4
    - otp_release: 23.3.1
      elixir: 1.11.4
env:
  global:
    - MIX_ENV=test
script:
  # Install dependencies
  - "mix deps.get"
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
  # Ensure code is formatted
  - >
    if [[ $(elixir -v) == *"Elixir 1.11.4"* ]]; then
      mix format --check-formatted
    fi
